### ISSUE TITLE
How to run it in Dev mode

### ISSUE THREAD

**Issue by newtonsheikh** [mohitbagra/vsts-extension-react-widgets#3]
how do I run it dev mode. 

can I have the step by step tutorials? I am really new to vsts extensions with react

**Comment by mohitbagra** [comment]
SInce this is a vsts specific library, it'll only run as a VSTS extension. I do have some demos of my components in the "demo" folder. To run the demo -
1. Fork the code
2. Run "npm install" from the repo root
3. open "demo/vss-extension.json" file and change the publisher name to your vsts publisher name. You need to do this to install the demo extension in VSTS
4. from repo root, run "npm run package:demo". This will generate a vsix for the demo extension. You can then either upload it to VSTS marketplace and share with your VSTS account or if you are on TFS, you can just upload the extension in your local TFS "manage extensions" page and install it.
5. run "npm start" to start the local webpack dev server

Once you install the demo extension, you'll see it under "Work hub" named "React Widgets Demo". All the samples are under that hub.

Note that the local web server runs as https so you'll need to trust the localhost certificate in browser to make it run.

**Comment by mohitbagra** [comment]
And on a side note, right now only I am using this library in my own extensions so I frequently make  changes to it and sometimes they would be breaking changes. If you dont want my breaking changes being pulled frequently, feel free to fork this repo

**Comment by newtonsheikh** [comment]
Thanks a ton Mohit. Have been using your code as a boilerplate for my own extension here. Its a great help of how to actually start enterpise level extension. The walkthroughs and tutorials on MSDN are well too basic and extremely less informative. Thanks again. Keep sharing keep inspiring. Have a good day. Cheers

**Comment by mohitbagra** [comment]
Glad to have helped. If you want some more guidance, I have 2 more colleagues who have written quite a few vsts extensions.
https://github.com/cschleiden
https://github.com/ostreifel

In case you are looking for something that I have not covered yet.
